import { ContractData } from './types';

// PROCUREMENT INDUSTRY DATA
export const procurementContracts: ContractData[] = [
  {
    id: 'proc-msa-001',
    type: 'MSA',
    title: 'Master Services Agreement - Enterprise Software Solutions',
    firstParty: 'GlobalTech Corporation',
    thirdParty: 'CloudSync Solutions LLC',
    effectiveDate: '2024-01-01',
    expirationDate: '2026-12-31',
    governingLaw: 'New York State Law',
    paymentTerms: 'Net 30 days from invoice receipt',
    terminationClause: 'Either party may terminate with 60 days written notice',
    confidentialityClause: 'Standard mutual NDA with 7-year post-termination period',
    indemnificationClause: 'Mutual indemnification with $5M liability cap',
    status: 'Active',
    totalValue: 15000000,
    currency: 'USD',
    industry: 'Procurement',
    contractManager: 'Sarah Chen, Director of Procurement',
    renewalNotice: 'Automatic renewal unless 90-day notice provided',
    performanceMetrics: ['Service Level Agreement 99.5%', 'Response Time <2 hours', 'Customer Satisfaction >4.5/5'],
    complianceRequirements: ['SOC 2 Type II', 'ISO 27001', 'GDPR Compliance', 'Annual Security Assessment'],
    riskLevel: 'Medium',
    vendorRating: 'Preferred - Tier 1 Strategic Partner',
    businessUnit: 'Information Technology Division',
    projectCode: 'PROJ-2024-CLOUD-001',
    approvalAuthority: 'CTO and Procurement Committee',
    children: [
      {
        id: 'proc-sow-001',
        type: 'SOW',
        title: 'Cloud Infrastructure Migration - Phase 1',
        firstParty: 'GlobalTech Corporation',
        thirdParty: 'CloudSync Solutions LLC',
        effectiveDate: '2024-02-15',
        expirationDate: '2024-08-15',
        governingLaw: 'New York State Law',
        paymentTerms: 'Milestone-based payments within 15 days',
        terminationClause: 'Termination for convenience with 45 days notice',
        confidentialityClause: 'Per MSA confidentiality terms',
        indemnificationClause: 'Per MSA indemnification terms',
        parentContractId: 'proc-msa-001',
        status: 'Active',
        totalValue: 2500000,
        currency: 'USD',
        industry: 'Procurement',
        contractManager: 'Mike Rodriguez, IT Project Manager',
        deliverables: ['AWS Infrastructure Setup', '500 Virtual Machines', 'Load Balancer Configuration', 'Backup & DR Setup'],
        keyMilestones: [
          { date: '2024-03-15', description: 'Infrastructure Assessment Complete', completed: true },
          { date: '2024-05-01', description: 'Phase 1 Migration (50% of systems)', completed: true },
          { date: '2024-06-30', description: 'Phase 2 Migration (remaining systems)', completed: false },
          { date: '2024-08-15', description: 'Full Testing and Go-Live', completed: false }
        ],
        performanceMetrics: ['99.9% Uptime SLA', 'Migration within 6-month timeline', '<4 hour downtime per migration'],
        riskLevel: 'High',
        businessUnit: 'Cloud Infrastructure Team',
        projectCode: 'PROJ-2024-CLOUD-001-SOW1',
        children: [
          {
            id: 'proc-co-001',
            type: 'ChangeOrder',
            title: 'Additional Security Compliance Requirements',
            firstParty: 'GlobalTech Corporation',
            thirdParty: 'CloudSync Solutions LLC',
            effectiveDate: '2024-04-01',
            governingLaw: 'New York State Law',
            paymentTerms: 'Payment due within 15 days of milestone completion',
            terminationClause: 'As per parent SOW terms',
            confidentialityClause: 'As per parent SOW terms',
            indemnificationClause: 'As per parent SOW terms',
            parentContractId: 'proc-sow-001',
            status: 'Active',
            totalValue: 350000,
            currency: 'USD',
            industry: 'Procurement',
            contractManager: 'Mike Rodriguez, IT Project Manager',
            deliverables: ['PCI-DSS Compliance Setup', 'Enhanced Firewalls', 'Security Monitoring Tools', 'Compliance Documentation'],
            complianceRequirements: ['PCI-DSS Level 1', 'SOX Compliance', 'Third-party Security Audit'],
            riskLevel: 'Critical',
            approvalAuthority: 'CISO and Security Committee',
            children: [
              {
                id: 'proc-amend-001',
                type: 'Amendment',
                title: 'Extended Compliance Testing Period',
                firstParty: 'GlobalTech Corporation',
                thirdParty: 'CloudSync Solutions LLC',
                effectiveDate: '2024-05-15',
                governingLaw: 'New York State Law',
                paymentTerms: 'Additional $50K upon completion',
                terminationClause: 'As per parent Change Order terms',
                confidentialityClause: 'As per parent Change Order terms',
                indemnificationClause: 'As per parent Change Order terms',
                parentContractId: 'proc-co-001',
                status: 'Active',
                totalValue: 50000,
                currency: 'USD',
                industry: 'Procurement',
                contractManager: 'Mike Rodriguez, IT Project Manager',
                deliverables: ['Extended Penetration Testing', 'Vulnerability Assessment Report', 'Remediation Plan'],
                keyMilestones: [
                  { date: '2024-05-20', description: 'Extended Testing Period Start', completed: true },
                  { date: '2024-06-15', description: 'Final Security Report', completed: false }
                ],
                riskLevel: 'Medium'
              }
            ]
          },
          {
            id: 'proc-co-002',
            type: 'ChangeOrder',
            title: 'Data Center Redundancy Enhancement',
            firstParty: 'GlobalTech Corporation',
            thirdParty: 'CloudSync Solutions LLC',
            effectiveDate: '2024-03-20',
            governingLaw: 'New York State Law',
            paymentTerms: 'Payment due within 15 days of completion',
            terminationClause: 'As per parent SOW terms',
            confidentialityClause: 'As per parent SOW terms',
            indemnificationClause: 'As per parent SOW terms',
            parentContractId: 'proc-sow-001',
            status: 'Active',
            totalValue: 185000,
            currency: 'USD',
            industry: 'Procurement',
            contractManager: 'Mike Rodriguez, IT Project Manager',
            deliverables: ['Secondary Data Center Setup', 'Disaster Recovery Testing', 'Failover Procedures', 'Business Continuity Plan'],
            performanceMetrics: ['RTO < 4 hours', 'RPO < 1 hour', '99.99% Data Integrity'],
            riskLevel: 'High',
            businessUnit: 'Infrastructure Resilience Team'
          }
        ]
      }
    ]
  }
];

// MANUFACTURING INDUSTRY DATA
export const manufacturingContracts: ContractData[] = [
  {
    id: 'mfg-prime-001',
    type: 'PrimeContract',
    title: 'Defense Systems Manufacturing Contract',
    firstParty: 'U.S. Department of Defense',
    thirdParty: 'AeroDefense Industries Inc.',
    effectiveDate: '2023-10-01',
    expirationDate: '2026-09-30',
    governingLaw: 'Federal Acquisition Regulations (FAR)',
    paymentTerms: 'Progress payments per FAR 32.503',
    terminationClause: 'Government termination rights per FAR 52.249',
    confidentialityClause: 'Classified information handling per security agreement',
    indemnificationClause: 'Limited government liability per sovereign immunity',
    status: 'Active',
    totalValue: 125000000,
    currency: 'USD',
    industry: 'Manufacturing',
    contractManager: 'Colonel James Mitchell, Defense Contract Administration',
    performanceMetrics: ['On-time Delivery 98%', 'Quality Rating >99.5%', 'Cost Performance Index >0.95'],
    complianceRequirements: ['ITAR', 'DFARS', 'AS9100D', 'CMMC Level 3', 'Buy American Act'],
    riskLevel: 'Critical',
    businessUnit: 'Defense Systems Division',
    projectCode: 'DEF-2023-RADAR-001',
    approvalAuthority: 'Defense Contract Management Agency',
    children: [
      {
        id: 'mfg-sub-001',
        type: 'SubcontractMSA',
        title: 'Electronic Components Supply Agreement',
        firstParty: 'AeroDefense Industries Inc.',
        thirdParty: 'TechComponents Corp',
        effectiveDate: '2023-11-15',
        expirationDate: '2026-09-30',
        governingLaw: 'California State Law',
        paymentTerms: 'Net 45 days following prime contract payment',
        terminationClause: 'Termination for convenience with 90 days notice',
        confidentialityClause: 'Proprietary information protection for 10 years',
        indemnificationClause: 'Full indemnification for IP infringement claims',
        parentContractId: 'mfg-prime-001',
        status: 'Active',
        totalValue: 18500000,
        currency: 'USD',
        industry: 'Manufacturing',
        contractManager: 'Lisa Wong, Supply Chain Director',
        renewalNotice: 'Subject to prime contract performance and funding availability',
        performanceMetrics: ['First Pass Yield >95%', 'Delivery Performance >98%', 'Cost Variance <2%'],
        complianceRequirements: ['AS9100D', 'ITAR Registration', 'Counterfeit Parts Prevention', 'Conflict Minerals Reporting'],
        riskLevel: 'High',
        vendorRating: 'Key Supplier - Strategic Partnership',
        businessUnit: 'Electronic Systems Manufacturing',
        children: [
          {
            id: 'mfg-po-001',
            type: 'PurchaseOrder',
            title: 'Radar System Components - Lot 1',
            firstParty: 'AeroDefense Industries Inc.',
            thirdParty: 'TechComponents Corp',
            effectiveDate: '2024-01-10',
            expirationDate: '2024-06-30',
            governingLaw: 'California State Law',
            paymentTerms: 'Net 30 days upon delivery and acceptance',
            terminationClause: 'Cancellation rights per purchase terms',
            confidentialityClause: 'Per master subcontract agreement',
            indemnificationClause: 'Per master subcontract agreement',
            parentContractId: 'mfg-sub-001',
            status: 'Active',
            totalValue: 2800000,
            currency: 'USD',
            industry: 'Manufacturing',
            contractManager: 'David Park, Manufacturing Engineer',
            deliverables: ['150 Radar Transmitter Units', '200 Signal Processing Boards', '100 Power Supply Modules', 'Technical Documentation Package'],
            keyMilestones: [
              { date: '2024-02-01', description: 'First Article Inspection', completed: true },
              { date: '2024-04-15', description: '50% Production Delivery', completed: true },
              { date: '2024-06-30', description: 'Final Delivery and Acceptance', completed: false }
            ],
            complianceRequirements: ['First Article Inspection', 'Government Source Inspection', 'Certificate of Conformance'],
            riskLevel: 'Medium',
            children: [
              {
                id: 'mfg-flow-001',
                type: 'FlowdownAmendment',
                title: 'Enhanced Quality Control Requirements',
                firstParty: 'AeroDefense Industries Inc.',
                thirdParty: 'TechComponents Corp',
                effectiveDate: '2024-02-28',
                governingLaw: 'California State Law',
                paymentTerms: 'Additional quality premium of 3%',
                terminationClause: 'As per parent PO terms',
                confidentialityClause: 'As per parent PO terms',
                indemnificationClause: 'Enhanced warranty provisions',
                parentContractId: 'mfg-po-001',
                status: 'Active',
                totalValue: 84000,
                currency: 'USD',
                industry: 'Manufacturing',
                contractManager: 'David Park, Manufacturing Engineer',
                deliverables: ['Enhanced QC Procedures', 'Statistical Process Control Implementation', 'Quality Management System Updates'],
                complianceRequirements: ['ISO 9001:2015', 'AS9100D Rev D', 'Customer-Specific Quality Requirements'],
                performanceMetrics: ['Zero Defect Goal', 'Cpk >1.67 for Critical Characteristics'],
                riskLevel: 'Low'
              }
            ]
          },
          {
            id: 'mfg-po-002',
            type: 'PurchaseOrder',
            title: 'Navigation Systems - Lot 2',
            firstParty: 'AeroDefense Industries Inc.',
            thirdParty: 'TechComponents Corp',
            effectiveDate: '2024-03-01',
            expirationDate: '2024-09-15',
            governingLaw: 'California State Law',
            paymentTerms: 'Net 30 days upon delivery and acceptance',
            terminationClause: 'Cancellation rights per purchase terms',
            confidentialityClause: 'Per master subcontract agreement',
            indemnificationClause: 'Per master subcontract agreement',
            parentContractId: 'mfg-sub-001',
            status: 'Active',
            totalValue: 3200000,
            currency: 'USD',
            industry: 'Manufacturing',
            contractManager: 'David Park, Manufacturing Engineer',
            deliverables: ['75 Navigation Computer Units', '150 Inertial Measurement Units', '200 GPS Receiver Modules', 'Integration Test Equipment'],
            keyMilestones: [
              { date: '2024-04-01', description: 'Design Review and Approval', completed: true },
              { date: '2024-07-15', description: '75% Production Milestone', completed: false },
              { date: '2024-09-15', description: 'Final Delivery and Testing', completed: false }
            ],
            riskLevel: 'Medium',
            businessUnit: 'Navigation Systems Division'
          }
        ]
      },
      {
        id: 'mfg-sub-002',
        type: 'SubcontractMSA',
        title: 'Mechanical Systems Manufacturing',
        firstParty: 'AeroDefense Industries Inc.',
        thirdParty: 'Precision Manufacturing Ltd.',
        effectiveDate: '2023-12-01',
        expirationDate: '2026-09-30',
        governingLaw: 'Texas State Law',
        paymentTerms: 'Net 30 days following prime contract payment',
        terminationClause: 'Termination for convenience with 60 days notice',
        confidentialityClause: 'Trade secret protection for 15 years',
        indemnificationClause: 'Mutual indemnification with $2M cap',
        parentContractId: 'mfg-prime-001',
        status: 'Active',
        totalValue: 25000000,
        currency: 'USD',
        industry: 'Manufacturing',
        contractManager: 'Robert Chen, Mechanical Systems Director',
        performanceMetrics: ['Precision Tolerance ±0.001"', 'Surface Finish Ra 32', 'Material Traceability 100%'],
        complianceRequirements: ['NADCAP Accreditation', 'Special Process Certifications', 'Material Test Certificates'],
        deliverables: ['Machined Aircraft Structures', 'Heat Treatment Services', 'Non-Destructive Testing', 'Assembly Services'],
        riskLevel: 'High',
        vendorRating: 'Critical Supplier - Sole Source',
        businessUnit: 'Structural Components Division'
      }
    ]
  }
];

// HEALTHCARE INDUSTRY DATA
export const healthcareContracts: ContractData[] = [
  {
    id: 'hc-master-001',
    type: 'MasterAffiliation',
    title: 'Regional Healthcare Network Master Affiliation Agreement',
    firstParty: 'Metropolitan Health System',
    thirdParty: 'Regional Medical Partners LLC',
    effectiveDate: '2023-07-01',
    expirationDate: '2028-06-30',
    governingLaw: 'Illinois State Law and Federal Healthcare Regulations',
    paymentTerms: 'Monthly settlements per agreed fee schedules',
    terminationClause: 'Termination with 18 months notice, subject to patient care continuity',
    confidentialityClause: 'HIPAA compliant PHI protection and business associate terms',
    indemnificationClause: 'Professional liability and regulatory compliance indemnification',
    status: 'Active',
    totalValue: 450000000,
    currency: 'USD',
    industry: 'Healthcare',
    contractManager: 'Dr. Patricia Williams, Chief Medical Officer',
    renewalNotice: 'Renewal notification required 24 months prior to expiration',
    performanceMetrics: ['HCAHPS Score >85%', 'Readmission Rate <10%', 'Patient Safety Grade A', 'Quality Star Rating >4.0'],
    complianceRequirements: ['Joint Commission Accreditation', 'CMS Conditions of Participation', 'HIPAA Privacy & Security Rules', 'Stark Law Compliance'],
    riskLevel: 'High',
    businessUnit: 'Network Operations Division',
    approvalAuthority: 'Board of Directors and Regulatory Affairs Committee',
    children: [
      {
        id: 'hc-facility-001',
        type: 'FacilityAgreement',
        title: 'Central Campus Medical Center Facility Agreement',
        firstParty: 'Metropolitan Health System',
        thirdParty: 'Regional Medical Partners LLC',
        effectiveDate: '2023-08-01',
        expirationDate: '2028-06-30',
        governingLaw: 'Illinois State Law and CMS Regulations',
        paymentTerms: 'Shared revenue model with monthly reconciliation',
        terminationClause: 'Aligned with master affiliation terms',
        confidentialityClause: 'Per master affiliation HIPAA terms',
        indemnificationClause: 'Facility-specific liability coverage requirements',
        parentContractId: 'hc-master-001',
        status: 'Active',
        totalValue: 125000000,
        currency: 'USD',
        industry: 'Healthcare',
        contractManager: 'Jennifer Martinez, Director of Medical Affairs',
        performanceMetrics: ['Bed Occupancy Rate >85%', 'Average Length of Stay <4.2 days', 'Patient Satisfaction >90%', 'Physician Recruitment >95%'],
        complianceRequirements: ['Joint Commission Standards', 'CMS Quality Reporting', 'State Health Department Licensing', 'DNV GL Accreditation'],
        deliverables: ['24/7 Emergency Services', 'Inpatient & Outpatient Care', 'Diagnostic Services', 'Surgical Services'],
        riskLevel: 'Medium',
        businessUnit: 'Central Campus Operations',
        children: [
          {
            id: 'hc-physician-001',
            type: 'PhysicianAgreement',
            title: 'Cardiology Department Physician Services',
            firstParty: 'Metropolitan Health System',
            thirdParty: 'Dr. Sarah Johnson, MD - Cardiology Associates',
            effectiveDate: '2023-09-01',
            expirationDate: '2026-08-31',
            governingLaw: 'Illinois Medical Practice Act and Federal Stark Law',
            paymentTerms: 'Base salary plus productivity incentives, paid bi-weekly',
            terminationClause: 'Termination with 90 days notice or immediate for cause',
            confidentialityClause: 'Patient confidentiality and proprietary medical protocols',
            indemnificationClause: 'Professional malpractice coverage and hospital indemnification',
            parentContractId: 'hc-facility-001',
            status: 'Active',
            totalValue: 850000,
            currency: 'USD',
            industry: 'Healthcare',
            contractManager: 'Dr. Michael Torres, Department Chair - Cardiology',
            performanceMetrics: ['RVU Production >8000 annually', 'Patient Satisfaction >4.5/5', 'Peer Review Score >Satisfactory', 'CME Requirements 50 hours annually'],
            complianceRequirements: ['Board Certification Maintenance', 'Medical License in Good Standing', 'Hospital Privileges', 'Malpractice Insurance $2M/$6M'],
            deliverables: ['Clinical Services', 'Teaching & Mentoring', 'Quality Improvement Participation', 'Committee Service'],
            riskLevel: 'Medium',
            businessUnit: 'Cardiovascular Services Division',
            children: [
              {
                id: 'hc-comp-001',
                type: 'CompensationSchedule',
                title: 'Cardiology Productivity Incentive Schedule 2024',
                firstParty: 'Metropolitan Health System',
                thirdParty: 'Dr. Sarah Johnson, MD',
                effectiveDate: '2024-01-01',
                expirationDate: '2024-12-31',
                governingLaw: 'Illinois State Law',
                paymentTerms: 'Quarterly bonuses based on RVU production and quality metrics',
                terminationClause: 'Pro-rated payments upon early termination',
                confidentialityClause: 'Compensation information confidentiality',
                indemnificationClause: 'As per parent physician agreement',
                parentContractId: 'hc-physician-001',
                status: 'Active',
                totalValue: 125000,
                currency: 'USD',
                industry: 'Healthcare',
                contractManager: 'Angela Roberts, Physician Compensation Manager',
                performanceMetrics: ['RVU Target: >8000/year', 'Quality Score >4.0/5', 'Patient Volume Target: 1200/year'],
                keyMilestones: [
                  { date: '2024-03-31', description: 'Q1 Performance Review', completed: true },
                  { date: '2024-06-30', description: 'Q2 Performance Review', completed: false },
                  { date: '2024-09-30', description: 'Q3 Performance Review', completed: false }
                ],
                deliverables: ['Quarterly Incentive Payments', 'Annual Performance Bonus', 'Quality Metric Bonuses'],
                riskLevel: 'Low'
              },
              {
                id: 'hc-sla-001',
                type: 'SLA',
                title: 'Cardiac Catheterization Lab Service Level Agreement',
                firstParty: 'Metropolitan Health System',
                thirdParty: 'Dr. Sarah Johnson, MD',
                effectiveDate: '2024-01-01',
                expirationDate: '2024-12-31',
                governingLaw: 'Illinois State Law and Joint Commission Standards',
                paymentTerms: 'Performance-based adjustments to base compensation',
                terminationClause: 'Modification allowed with 30 days notice',
                confidentialityClause: 'Quality metrics and patient outcome data protection',
                indemnificationClause: 'Quality assurance peer review protection',
                parentContractId: 'hc-physician-001',
                status: 'Active',
                totalValue: 0,
                currency: 'USD',
                industry: 'Healthcare',
                contractManager: 'Dr. Michael Torres, Department Chair - Cardiology',
                performanceMetrics: ['Procedure Volume: >500 cases/year', 'Door-to-Balloon Time <90 min', 'Complication Rate <2%', 'Patient Satisfaction >95%'],
                complianceRequirements: ['Joint Commission Cath Lab Standards', 'ACC/AHA Guidelines', 'Radiation Safety Protocols'],
                deliverables: ['24/7 On-Call Coverage', 'Emergency Procedure Availability', 'Quality Reporting', 'Staff Training'],
                keyMilestones: [
                  { date: '2024-04-01', description: 'Q1 Quality Review', completed: true },
                  { date: '2024-07-01', description: 'Mid-Year Performance Assessment', completed: false }
                ],
                riskLevel: 'Medium'
              }
            ]
          },
          {
            id: 'hc-physician-002',
            type: 'PhysicianAgreement',
            title: 'Emergency Department Physician Services',
            firstParty: 'Metropolitan Health System',
            thirdParty: 'Emergency Medicine Group LLC',
            effectiveDate: '2023-10-01',
            expirationDate: '2026-09-30',
            governingLaw: 'Illinois Medical Practice Act and EMTALA',
            paymentTerms: 'Hourly rate plus call coverage stipend',
            terminationClause: 'Termination with 120 days notice for operational continuity',
            confidentialityClause: 'Patient confidentiality and emergency protocols',
            indemnificationClause: 'Professional liability and EMTALA compliance coverage',
            parentContractId: 'hc-facility-001',
            status: 'Active',
            totalValue: 2400000,
            currency: 'USD',
            industry: 'Healthcare',
            contractManager: 'Dr. Rachel Kim, Emergency Department Director',
            performanceMetrics: ['Door-to-Doc Time <15 min', 'Length of Stay <4 hours', 'Left Without Being Seen <5%', 'Patient Satisfaction >85%'],
            complianceRequirements: ['EMTALA Compliance', 'Emergency Medicine Board Certification', 'ACLS/PALS Certification', 'Trauma Certification'],
            deliverables: ['24/7 Emergency Coverage', 'Trauma Response', 'Critical Care Stabilization', 'Transfer Coordination'],
            riskLevel: 'High',
            businessUnit: 'Emergency Services Division'
          }
        ]
      },
      {
        id: 'hc-facility-002',
        type: 'FacilityAgreement',
        title: 'Suburban Clinic Network Facility Agreement',
        firstParty: 'Metropolitan Health System',
        thirdParty: 'Regional Medical Partners LLC',
        effectiveDate: '2023-09-01',
        expirationDate: '2028-06-30',
        governingLaw: 'Illinois State Law and Federal Quality Payment Program',
        paymentTerms: 'Capitation model with quality bonuses',
        terminationClause: 'Aligned with master affiliation terms',
        confidentialityClause: 'Per master affiliation HIPAA terms',
        indemnificationClause: 'Ambulatory care liability requirements',
        parentContractId: 'hc-master-001',
        status: 'Active',
        totalValue: 75000000,
        currency: 'USD',
        industry: 'Healthcare',
        contractManager: 'Maria Santos, Ambulatory Care Director',
        performanceMetrics: ['Patient Access <14 days', 'Preventive Care Rates >80%', 'Chronic Care Management >90%', 'Cost per Visit <$180'],
        complianceRequirements: ['PCMH Certification', 'HEDIS Quality Measures', 'Meaningful Use Requirements', 'Value-Based Care Reporting'],
        deliverables: ['Primary Care Services', 'Specialty Consultations', 'Diagnostic Services', 'Care Coordination'],
        riskLevel: 'Medium',
        businessUnit: 'Community Health Division'
      }
    ]
  }
];

// CONSTRUCTION INDUSTRY DATA
export const constructionContracts: ContractData[] = [
  {
    id: 'con-prime-001',
    type: 'PrimeConstruction',
    title: 'Metropolitan Office Tower Development',
    firstParty: 'Metro Development Corporation',
    thirdParty: 'BuildMax Construction LLC',
    effectiveDate: '2024-01-15',
    expirationDate: '2026-06-30',
    governingLaw: 'New York Construction Lien Law and AIA Standards',
    paymentTerms: 'Monthly progress payments based on completed work, net 30 days',
    terminationClause: 'Owner termination for convenience with 30 days notice plus costs',
    confidentialityClause: 'Proprietary building designs and tenant information protection',
    indemnificationClause: 'Mutual indemnification with $10M professional liability coverage',
    status: 'Active',
    totalValue: 85000000,
    currency: 'USD',
    industry: 'Construction',
    contractManager: 'James Patterson, Senior Project Manager',
    performanceMetrics: ['Schedule Performance Index >0.95', 'Cost Performance Index >0.90', 'Safety Rating >4.5/5', 'Quality Score >95%'],
    complianceRequirements: ['NYC Building Code', 'OSHA 30-Hour Certification', 'LEED Gold Certification', 'Prevailing Wage Compliance'],
    deliverables: ['42-Story Office Tower', 'Underground Parking Garage', 'Retail Space', 'HVAC & Building Systems'],
    riskLevel: 'High',
    businessUnit: 'Commercial Construction Division',
    projectCode: 'METRO-2024-OFC-001',
    approvalAuthority: 'Board of Directors and Construction Committee',
    keyMilestones: [
      { date: '2024-03-01', description: 'Foundation Completion', completed: true },
      { date: '2024-08-15', description: 'Structural Steel Completion', completed: true },
      { date: '2024-12-01', description: 'Building Envelope Completion', completed: false },
      { date: '2025-06-01', description: 'Mechanical/Electrical Completion', completed: false }
    ],
    children: [
      {
        id: 'con-sub-001',
        type: 'Subcontract',
        title: 'Structural Steel & Concrete Work',
        firstParty: 'BuildMax Construction LLC',
        thirdParty: 'SteelCore Structural Inc.',
        effectiveDate: '2024-02-01',
        expirationDate: '2024-10-31',
        governingLaw: 'New York State Law and AIA A401',
        paymentTerms: 'Pay-when-paid within 7 days of owner payment',
        terminationClause: 'Termination for default with 10 days cure period',
        confidentialityClause: 'Project-specific information and design confidentiality',
        indemnificationClause: 'Full indemnification for structural work with $5M coverage',
        parentContractId: 'con-prime-001',
        status: 'Active',
        totalValue: 18500000,
        currency: 'USD',
        industry: 'Construction',
        contractManager: 'Maria Rodriguez, Structural Superintendent',
        performanceMetrics: ['Zero Lost Time Accidents', 'Concrete Strength >4000 PSI', 'Steel Erection Rate >2 floors/week'],
        complianceRequirements: ['AWS Certified Welders', 'Structural Steel Painting Standards', 'Concrete Testing & QA/QC'],
        deliverables: ['Structural Steel Frame', 'Concrete Foundation & Floors', 'Fireproofing', 'Anchor Bolt Installation'],
        riskLevel: 'High',
        businessUnit: 'Structural Division',
        children: [
          {
            id: 'con-trade-001',
            type: 'TradeAgreement',
            title: 'Ironworker Local 40 Trade Agreement',
            firstParty: 'SteelCore Structural Inc.',
            thirdParty: 'Ironworkers Local 40 Union',
            effectiveDate: '2024-02-01',
            expirationDate: '2024-10-31',
            governingLaw: 'New York Labor Law and Collective Bargaining Agreement',
            paymentTerms: 'Weekly payroll with prevailing wage rates',
            terminationClause: 'Per collective bargaining agreement terms',
            confidentialityClause: 'Project safety and operational procedures',
            indemnificationClause: 'Workers compensation and union liability coverage',
            parentContractId: 'con-sub-001',
            status: 'Active',
            totalValue: 3200000,
            currency: 'USD',
            industry: 'Construction',
            contractManager: 'Tony Battaglia, Labor Relations Supervisor',
            performanceMetrics: ['Zero Safety Violations', 'Productivity >85% of standard', 'Quality Workmanship Rating >4.5/5'],
            complianceRequirements: ['Prevailing Wage Requirements', 'Union Apprenticeship Programs', 'OSHA 10 & 30 Hour Training'],
            deliverables: ['Steel Erection Services', 'Rigging & Hoisting', 'Welding Services', 'Safety Compliance'],
            riskLevel: 'Medium',
            businessUnit: 'Labor Relations',
            children: [
              {
                id: 'con-amend-001',
                type: 'ConstructionAmendment',
                title: 'Weekend Overtime Authorization',
                firstParty: 'SteelCore Structural Inc.',
                thirdParty: 'Ironworkers Local 40 Union',
                effectiveDate: '2024-07-01',
                governingLaw: 'New York Labor Law',
                paymentTerms: 'Double-time rates for weekend work',
                terminationClause: 'Amendment expires with project completion',
                confidentialityClause: 'Overtime scheduling and project timeline confidentiality',
                indemnificationClause: 'Extended coverage for weekend operations',
                parentContractId: 'con-trade-001',
                status: 'Active',
                totalValue: 280000,
                currency: 'USD',
                industry: 'Construction',
                contractManager: 'Tony Battaglia, Labor Relations Supervisor',
                deliverables: ['Weekend Steel Erection', 'Accelerated Schedule Compliance', 'Safety Protocol Maintenance'],
                riskLevel: 'Medium'
              }
            ]
          }
        ]
      },
      {
        id: 'con-sub-002',
        type: 'Subcontract',
        title: 'MEP (Mechanical, Electrical, Plumbing) Systems',
        firstParty: 'BuildMax Construction LLC',
        thirdParty: 'PowerFlow MEP Contractors',
        effectiveDate: '2024-06-01',
        expirationDate: '2025-12-31',
        governingLaw: 'New York State Law and NEC/NYC Electrical Code',
        paymentTerms: 'Monthly progress payments, pay-when-paid basis',
        terminationClause: 'Termination for convenience with 60 days notice',
        confidentialityClause: 'Building systems and tenant specification confidentiality',
        indemnificationClause: 'Professional liability and system performance guarantees',
        parentContractId: 'con-prime-001',
        status: 'Active',
        totalValue: 15800000,
        currency: 'USD',
        industry: 'Construction',
        contractManager: 'David Kim, MEP Project Manager',
        performanceMetrics: ['Energy Efficiency Rating >LEED Gold', 'System Commissioning >99%', 'Code Compliance 100%'],
        complianceRequirements: ['Licensed Master Electrician', 'NYC DEP Plumbing Permits', 'Energy Code Compliance'],
        deliverables: ['HVAC Systems', 'Electrical Distribution', 'Plumbing & Fire Protection', 'Building Automation'],
        riskLevel: 'High',
        businessUnit: 'MEP Division',
        vendorRating: 'Preferred Contractor - Tier 1'
      }
    ]
  }
];

// ENERGY & OIL/GAS INDUSTRY DATA
export const energyContracts: ContractData[] = [
  {
    id: 'eng-msa-001',
    type: 'EnergyMSA',
    title: 'Gulf Coast Offshore Drilling Services Master Agreement',
    firstParty: 'PetroMax Energy Corporation',
    thirdParty: 'DeepWater Drilling Services LLC',
    effectiveDate: '2023-08-01',
    expirationDate: '2028-07-31',
    governingLaw: 'Texas Maritime Law and Federal OCS Regulations',
    paymentTerms: 'Monthly invoicing with net 45 days payment terms',
    terminationClause: 'Termination for cause with 30 days notice, convenience 180 days',
    confidentialityClause: 'Geological data and drilling technology proprietary information',
    indemnificationClause: 'Comprehensive mutual indemnification with $50M coverage',
    status: 'Active',
    totalValue: 750000000,
    currency: 'USD',
    industry: 'Energy',
    contractManager: 'Sarah Mitchell, Senior Drilling Operations Manager',
    renewalNotice: 'Automatic 2-year renewal unless 12-month notice provided',
    performanceMetrics: ['HSE Performance >99.5%', 'Drilling Efficiency >85%', 'Zero Spill Incidents', 'Uptime >95%'],
    complianceRequirements: ['BSEE Regulations', 'API RP Standards', 'Environmental Impact Compliance', 'USCG Vessel Standards'],
    riskLevel: 'Critical',
    businessUnit: 'Upstream Operations Division',
    projectCode: 'GULF-2023-DRILL-001',
    approvalAuthority: 'Executive Committee and HSE Board',
    vendorRating: 'Strategic Partner - Critical Operations',
    children: [
      {
        id: 'eng-proj-001',
        type: 'ProjectAgreement',
        title: 'Thunderhorse South Field Development',
        firstParty: 'PetroMax Energy Corporation',
        thirdParty: 'DeepWater Drilling Services LLC',
        effectiveDate: '2024-01-15',
        expirationDate: '2025-08-30',
        governingLaw: 'Texas Maritime Law and MMS Regulations',
        paymentTerms: 'Day rate plus performance bonuses, monthly billing',
        terminationClause: 'Early termination with well completion requirements',
        confidentialityClause: 'Reservoir data and production forecasting confidentiality',
        indemnificationClause: 'Project-specific risk allocation per drilling contract',
        parentContractId: 'eng-msa-001',
        status: 'Active',
        totalValue: 185000000,
        currency: 'USD',
        industry: 'Energy',
        contractManager: 'Robert Chen, Field Development Manager',
        performanceMetrics: ['Drilling Rate >150 ft/day', 'Non-Productive Time <5%', 'Environmental Compliance 100%'],
        complianceRequirements: ['Drilling Permit Compliance', 'Blowout Preventer Testing', 'Environmental Monitoring'],
        deliverables: ['6 Development Wells', 'Subsea Infrastructure', 'Production Testing', 'Well Completion'],
        keyMilestones: [
          { date: '2024-03-01', description: 'First Well Spud', completed: true },
          { date: '2024-06-15', description: 'Third Well Completion', completed: true },
          { date: '2024-10-01', description: 'Fifth Well Spud', completed: false },
          { date: '2025-02-15', description: 'Final Well Completion', completed: false }
        ],
        riskLevel: 'Critical',
        businessUnit: 'Field Development Team',
        children: [
          {
            id: 'eng-wo-001',
            type: 'WorkOrder',
            title: 'Well THS-04 Drilling Operations',
            firstParty: 'PetroMax Energy Corporation',
            thirdParty: 'DeepWater Drilling Services LLC',
            effectiveDate: '2024-07-01',
            expirationDate: '2024-09-15',
            governingLaw: 'Texas State Law and Federal Maritime Regulations',
            paymentTerms: 'Daily rate $850K plus cost reimbursables',
            terminationClause: 'Completion-based termination with safety provisions',
            confidentialityClause: 'Well-specific geological and production data',
            indemnificationClause: 'Drilling-specific liability and insurance requirements',
            parentContractId: 'eng-proj-001',
            status: 'Active',
            totalValue: 28500000,
            currency: 'USD',
            industry: 'Energy',
            contractManager: 'Lisa Park, Well Operations Supervisor',
            performanceMetrics: ['Target Depth: 18,500 ft', 'Drilling Rate >120 ft/day', 'Zero HSE Incidents'],
            complianceRequirements: ['Well Control Procedures', 'Mud Weight Management', 'Casing Program Compliance'],
            deliverables: ['Wellbore to TD', 'Logging Program', 'Completion Design', 'Production Testing'],
            riskLevel: 'High',
            businessUnit: 'Well Operations',
            children: [
              {
                id: 'eng-ft-001',
                type: 'FieldTicket',
                title: 'Directional Drilling Services - Week 28',
                firstParty: 'DeepWater Drilling Services LLC',
                thirdParty: 'Precision Directional Drilling Inc.',
                effectiveDate: '2024-07-15',
                expirationDate: '2024-07-21',
                governingLaw: 'Texas State Law',
                paymentTerms: 'Weekly service fees plus equipment rental',
                terminationClause: 'Service completion or safety termination',
                confidentialityClause: 'Directional survey and drilling parameter data',
                indemnificationClause: 'Service-specific liability allocation',
                parentContractId: 'eng-wo-001',
                status: 'Active',
                totalValue: 425000,
                currency: 'USD',
                industry: 'Energy',
                contractManager: 'Mike Torres, Drilling Engineer',
                deliverables: ['Directional Survey Services', 'MWD/LWD Operations', 'Wellbore Trajectory Control'],
                performanceMetrics: ['Survey Accuracy <0.5°', 'Tool Reliability >98%', 'Real-time Data Transmission'],
                riskLevel: 'Medium'
              }
            ]
          }
        ]
      }
    ]
  }
];

// FINANCIAL SERVICES INDUSTRY DATA
export const financialContracts: ContractData[] = [
  {
    id: 'fin-mta-001',
    type: 'MasterTradingAgreement',
    title: 'ISDA Master Agreement - Derivatives Trading',
    firstParty: 'Global Investment Bank Corp',
    thirdParty: 'Metropolitan Asset Management LLC',
    effectiveDate: '2023-06-01',
    expirationDate: '2028-05-31',
    governingLaw: 'New York State Law and English Law (for certain products)',
    paymentTerms: 'Daily mark-to-market settlements, T+2 payment cycle',
    terminationClause: 'Automatic termination events per ISDA provisions',
    confidentialityClause: 'Trading strategies and portfolio information confidentiality',
    indemnificationClause: 'Regulatory and operational risk indemnification',
    status: 'Active',
    totalValue: 2500000000,
    currency: 'USD',
    industry: 'Financial',
    contractManager: 'Alexandra Wong, Head of Derivatives Trading',
    renewalNotice: 'Annual review with automatic renewal unless 180-day notice',
    performanceMetrics: ['Credit Rating Maintenance >A-', 'Margin Call Response <4 hours', 'Settlement Rate >99.95%'],
    complianceRequirements: ['Dodd-Frank Compliance', 'EMIR Reporting', 'Basel III Capital Requirements', 'MiFID II Transaction Reporting'],
    riskLevel: 'Critical',
    businessUnit: 'Institutional Trading Division',
    approvalAuthority: 'Risk Committee and Board of Directors',
    vendorRating: 'Tier 1 Counterparty - Investment Grade',
    children: [
      {
        id: 'fin-sched-001',
        type: 'ProductSchedule',
        title: 'Interest Rate Derivatives Product Schedule',
        firstParty: 'Global Investment Bank Corp',
        thirdParty: 'Metropolitan Asset Management LLC',
        effectiveDate: '2023-06-01',
        expirationDate: '2028-05-31',
        governingLaw: 'New York State Law and ISDA Definitions',
        paymentTerms: 'Product-specific settlement and margin requirements',
        terminationClause: 'Per master agreement termination provisions',
        confidentialityClause: 'Interest rate strategy and hedging information',
        indemnificationClause: 'Product-specific operational risk allocation',
        parentContractId: 'fin-mta-001',
        status: 'Active',
        totalValue: 850000000,
        currency: 'USD',
        industry: 'Financial',
        contractManager: 'David Liu, Interest Rate Products Head',
        performanceMetrics: ['Notional Limits: $1B per transaction', 'Risk Limits: 1% VAR', 'Pricing Accuracy >99.9%'],
        complianceRequirements: ['CFTC Swap Dealer Registration', 'Central Clearing Requirements', 'Trade Repository Reporting'],
        deliverables: ['Interest Rate Swaps', 'Forward Rate Agreements', 'Interest Rate Options', 'Inflation Swaps'],
        riskLevel: 'High',
        businessUnit: 'Fixed Income Trading',
        children: [
          {
            id: 'fin-conf-001',
            type: 'TransactionConfirmation',
            title: '10Y USD Interest Rate Swap - $500M Notional',
            firstParty: 'Global Investment Bank Corp',
            thirdParty: 'Metropolitan Asset Management LLC',
            effectiveDate: '2024-08-15',
            expirationDate: '2034-08-15',
            governingLaw: 'New York State Law and ISDA 2021 Definitions',
            paymentTerms: 'Semi-annual fixed payments vs quarterly floating SOFR',
            terminationClause: 'Early termination per ISDA master agreement',
            confidentialityClause: 'Transaction terms and hedging strategy confidentiality',
            indemnificationClause: 'Transaction-specific credit and operational risk',
            parentContractId: 'fin-sched-001',
            status: 'Active',
            totalValue: 500000000,
            currency: 'USD',
            industry: 'Financial',
            contractManager: 'Jennifer Chen, Senior Trader - IRS',
            performanceMetrics: ['Daily MTM Reconciliation', 'Collateral Management <1 day', 'Trade Lifecycle >99% STP'],
            complianceRequirements: ['SEF Execution Requirements', 'Central Clearing via LCH', 'Daily Risk Reporting'],
            deliverables: ['Fixed Rate Payments: 4.25% Semi-Annual', 'Floating Rate: 3M SOFR + Spread', 'Daily Valuation', 'Collateral Management'],
            keyMilestones: [
              { date: '2024-08-15', description: 'Trade Execution', completed: true },
              { date: '2024-08-17', description: 'Central Clearing', completed: true },
              { date: '2025-02-15', description: 'First Payment Exchange', completed: false },
              { date: '2025-08-15', description: 'First Annual Review', completed: false }
            ],
            riskLevel: 'Medium',
            businessUnit: 'Swap Trading Desk',
            children: [
              {
                id: 'fin-nov-001',
                type: 'Novation',
                title: 'Partial Novation - $200M to Third Party',
                firstParty: 'Metropolitan Asset Management LLC',
                thirdParty: 'Pension Fund Solutions Ltd',
                effectiveDate: '2024-09-01',
                governingLaw: 'New York State Law',
                paymentTerms: 'Pro-rata payment obligations transfer',
                terminationClause: 'Novation completion transfers all obligations',
                confidentialityClause: 'Original transaction terms confidentiality maintained',
                indemnificationClause: 'Clean novation with no residual liability',
                parentContractId: 'fin-conf-001',
                status: 'Active',
                totalValue: 200000000,
                currency: 'USD',
                industry: 'Financial',
                contractManager: 'Michael Rodriguez, Portfolio Transfer Specialist',
                deliverables: ['Novation Documentation', 'Risk Transfer Confirmation', 'Regulatory Notifications'],
                performanceMetrics: ['Settlement Accuracy 100%', 'Documentation Completion <5 days'],
                complianceRequirements: ['Regulatory Approval', 'Credit Risk Assessment', 'Transfer Documentation'],
                riskLevel: 'Low'
              }
            ]
          }
        ]
      }
    ]
  }
];

export const industryData = {
  'Procurement': procurementContracts,
  'Manufacturing': manufacturingContracts,
  'Healthcare': healthcareContracts,
  'Construction': constructionContracts,
  'Energy': energyContracts,
  'Financial': financialContracts,
};

export const industryDescriptions = {
  'Procurement': {
    title: 'Procurement Contract Management',
    description: 'Enterprise software and services procurement with MSA framework, detailed SOWs, change orders, and contract amendments.',
    hierarchy: 'MSA → SOW → Change Order → Amendment',
    keyFeatures: [
      'Master Service Agreements with multiple SOWs',
      'Change order management for scope modifications', 
      'Amendment tracking for contract modifications',
      'Vendor performance and compliance monitoring'
    ]
  },
  'Manufacturing': {
    title: 'Manufacturing & Defense Contracts',
    description: 'Complex manufacturing relationships from prime contracts through subcontractor networks with purchase orders and flowdown requirements.',
    hierarchy: 'Prime Contract → Subcontract MSA → Purchase Order → Flowdown Amendment',
    keyFeatures: [
      'Prime contractor-subcontractor relationships',
      'Purchase order management with delivery schedules',
      'Flowdown clause compliance tracking',
      'Quality and regulatory requirement management'
    ]
  },
  'Healthcare': {
    title: 'Healthcare Provider Networks',
    description: 'Healthcare system affiliations with facility agreements, physician contracts, compensation schedules, and service level agreements.',
    hierarchy: 'Master Affiliation → Facility Agreement → Physician Agreement → Compensation/SLA',
    keyFeatures: [
      'Multi-facility healthcare network management',
      'Physician credentialing and compensation tracking',
      'Service level agreement monitoring',
      'Regulatory compliance and quality metrics'
    ]
  },
  'Construction': {
    title: 'Construction & Infrastructure',
    description: 'Large-scale construction projects with prime contractors, subcontractors, trade agreements, and specialized construction amendments.',
    hierarchy: 'Prime Contract → Subcontract → Trade Agreement → Construction Amendment',
    keyFeatures: [
      'Multi-tier contractor and subcontractor relationships',
      'Trade-specific agreements and union contracts',
      'Performance bond and lien waiver management',
      'Safety compliance and building code adherence'
    ]
  },
  'Energy': {
    title: 'Energy & Oil/Gas Operations',
    description: 'Complex energy sector contracts from master service agreements through field-level work orders and operational tickets.',
    hierarchy: 'Energy MSA → Project Agreement → Work Order → Field Ticket',
    keyFeatures: [
      'Upstream and downstream operational agreements',
      'Environmental and safety regulatory compliance',
      'Joint venture and revenue sharing structures',
      'Field-level operational work authorization'
    ]
  },
  'Financial': {
    title: 'Financial Services & Trading',
    description: 'Sophisticated financial instruments and trading relationships with ISDA frameworks, product schedules, and transaction confirmations.',
    hierarchy: 'Master Trading Agreement → Product Schedule → Transaction Confirmation → Novation',
    keyFeatures: [
      'ISDA master agreement frameworks',
      'Multi-asset class product structuring',
      'Real-time transaction confirmation and settlement',
      'Regulatory compliance and risk management'
    ]
  }
};